import React from 'react'

const ToS = () => {
  return (
    <div className='relative top-16 flex flex-col'>
      <h1>Google Play Terms of Service</h1>
      <p>March 15, 2023</p>
      <h2><strong>1. Introduction</strong></h2>
<p><strong>Applicable Terms.</strong> Thanks for using Google Play. Google Play is a service provided by Google LLC (<strong>&ldquo;Google&rdquo;</strong>, <strong>&ldquo;we&rdquo;</strong> or <strong>&ldquo;us&rdquo;</strong>), located at 1600 Amphitheatre Parkway, Mountain View, California 94043, USA. Your use of Google Play and the apps (including Android Instant Apps), system services, games, movies, books, magazines, or other digital content or services (referred to as <strong>"Content"</strong>) available through it is subject to these Google Play Terms of Service (&ldquo;<strong>Play ToS</strong>&rdquo;) and the <a href="https://www.google.com/intl/en/policies/terms/" rel="noopener" target="_blank">Google Terms of Service</a> (<strong>"Google ToS"</strong>) (together referred to as the <strong>&ldquo;Terms&rdquo;</strong>). Google Play is a &ldquo;service&rdquo; as described in the Google ToS. If there is any conflict between the Play ToS and the Google ToS, the Play ToS shall prevail.</p>
<h2><strong>2. Your Use of Google Play</strong></h2>
<p><strong>Access to and Use of Content.</strong> You may use Google Play to browse, locate, view, stream, or download Content for your mobile, computer, tv, watch, or other supported device (<strong>&ldquo;Device&rdquo;</strong>). To use Google Play, you will need a Device that meets the <a href="https://support.google.com/googleplay/answer/1727131?hl=en" rel="noopener" target="_blank">system and compatibility requirements</a> for the relevant Content, working Internet access, and compatible software. The availability of Content and features will vary between countries and not all Content or features may be available in your country. Some Content may be available to share with family members. Content may be offered by Google or made available by third-parties not affiliated with Google. Google is not responsible for and does not endorse any Content made available through Google Play that originates from a source other than Google.</p>
<p><strong>Age Restrictions.</strong> In order to use Google Play, you must have a valid Google account (&ldquo;<strong>Google Account</strong>&rdquo;), subject to the following <a href="https://support.google.com/accounts/answer/1350409?hl=en#topic=1350409" rel="noopener" target="_blank">age restrictions</a>. If you are considered a minor in your country, you must have your parent or legal guardian&rsquo;s permission to use Google Play and to accept the Terms. You must comply with any additional age restrictions that might apply for the use of specific Content or features on Google Play. Family managers and family members must meet these <a href="https://support.google.com/googleplay/answer/7007852?hl=en&amp;ref_topic=6209538" rel="noopener" target="_blank">additional requirements</a> as well.</p>
<p><strong>Third-Party Fees.</strong> You are responsible for any access or data fees incurred from third parties (such as your Internet provider or mobile carrier) in connection with your use and viewing of Content and Google Play.</p>
<p><strong>Updates.</strong> Google Play, related support libraries, or Content may need to be updated, for example, for bug fixes, enhanced functions, missing plug-ins and new versions (collectively, &ldquo;<strong>Updates</strong>&rdquo;). Such Updates may be necessary in order for you to use Google Play or to access, download, or use Content. By agreeing to these Terms and using Google Play, you agree to receive such Updates automatically. You may be able to manage Updates to certain Content via Settings in Google Play. If it is determined, however, that the Update will fix a critical security vulnerability or critical operability issue related to the Content, or will prevent abuse, the Update may be completed irrespective of your Update settings in Google Play or your Device. If another app store attempts to update Content that was initially downloaded from Google Play, you may receive a warning or such updates may be prevented entirely.</p>
<p><strong>Information about You.</strong> Google&rsquo;s <a href="https://www.google.com/intl/en/policies/privacy/" rel="noopener" target="_blank">Privacy Policy</a> explains how we treat your personal data and protect your privacy when using Google Play. Google may need to provide your personal information, such as your name and email address, to Providers for the purposes of processing your transactions or provisioning Content to you. Providers agree to use this information in accordance with their privacy policies.</p>
<p>If you are part of a family group on Google Play, your family members in the family group will be able to see certain information about you. If you are the family manager of a family group on Google Play, family members you invite to join the family group will see your name, photo, and e-mail address. If you join a family group as a family member, other family members will be able to see your name, photo, and e-mail address. Your family manager may also see your age and will see a record of all purchases you make using the designated family payment method, including a description of the Content purchased. If Content is available for family sharing and you share it with your family group, then all family members will be able to access the Content and see that you purchased it.</p>
<p><strong>Unauthorized Access to Accounts.</strong> You must keep your account details secure and must not share them with anyone else. You must not collect or harvest any personal data of any user of Google Play or of any user of other Google Services via Google Play, including account names.</p>
<p><strong>Disabled Accounts.</strong> If Google disables access to your account in accordance with the Terms (for example if you violate the Terms), you may be prevented from accessing Google Play, your account details or any files or other Content that is stored with your account. See the <a href="https://support.google.com/accounts/answer/40695">Help Center</a> for more information. If you are the family manager of a family on Google Play and Google disables access to your account, your family members may lose access to family features requiring a family group, such as a family payment method, family subscriptions, or Content shared by family members. If you are a family member of a family on Google Play and Google disables your account, your family members will lose access to Content you have shared with them.</p>
<p><strong>Malware protection.</strong> To protect you against malicious third party software, URLs, and other security issues, Google may receive information about your Device&rsquo;s network connections, potentially harmful URLs, the operating system, and apps installed on your Device through Google Play or from other sources. Google may warn you if it considers an app or URL to be unsafe, or Google may remove or block its installation on your Device if it is known to be harmful to devices, data or users. You can choose to disable some of these protections in the settings on your Device, however, Google may continue to receive information about apps installed through Google Play, and apps installed on your Device from other sources may continue to be analyzed for security issues without sending information to Google.</p>
<p><strong>Android Instant Apps. </strong>When you click on a link on your Device, Google Play may check if an applicable instant app exists and, if so, open the link within the instant app. Any code needed to run the portions of the instant app you access will be downloaded to your Device and kept on it temporarily. App details for an instant app can be found in the Google Play store. Android Instant Apps data and settings are synced to devices signed in with your Google account. You can choose to disable Android Instant Apps in the settings on your Device.</p>
<p><strong>Changes to these Terms.</strong>If the Play ToS change, you will be given at least 30 days notice, and the new Play ToS will be effective after such notice period. Your continued use of Google Play following such notice period will indicate your acceptance of the new Play ToS. The new Play ToS will apply to your use of all Content (including Content you have installed or purchased in the past) and all subsequent installs or purchases. If you do not agree with such changes, you will be given the opportunity to download the Content you previously purchased or installed and terminate your use of the Google Play. You may continue to view that copy of the Content on your Devices in accordance with the last version of the Play ToS that you accepted.</p>
<h2><strong>3. Purchases and Payments</strong></h2>
<p><strong>Free Content.</strong> Google may allow you to download, view or use Content free of charge on Google Play. Additional limitations may apply to your access and use of certain free Content.</p>
<p><strong>Purchase of Content</strong>. When you buy Content on or using Google Play you will enter into a separate sale contract based on these Terms (as applicable) with the seller which will be either:</p>
<p>(a) Google LLC; or</p>
<p>(b) provider of the Content (the "<strong>Provider</strong>"), including where Google LLC is acting as an agent for the Provider.</p>
<p>The separate sale contract is in addition to these Terms.</p>
<p>For sales where Google is acting as an agent for the Provider, the statement, in the Google ToS, that the Google ToS &ldquo;do not create any third party beneficiary rights&rdquo;, does not apply to your use of Google Play.</p>
<p>Your contract for the purchase and use of Content is completed once you receive the email from Google confirming your purchase of that Content, and performance of this contract begins as soon as the purchase is complete.</p>
<p><strong>Pre-orders. </strong>When you place a pre-order for Content, your contract for the purchase and use of that item is completed when the Content is made available to you, and you will be charged for the purchase at that time. You can cancel your pre-order at any time up to the point at which the Content becomes available to you. We will need to cancel your pre-order if the Content is withdrawn from sale through Google Play before it is made available and we reserve the right to cancel your order in the event the price changes before your order is fulfilled.</p>
<p><strong>Family Payment Method</strong>. If you are the family manager of a family group on Google Play, you will be required to set up a valid family payment method for your family members to use to purchase Content on Google Play and within apps. You will be responsible for all of your family members&rsquo; purchases of Content using the family payment method. If a family group is deleted, or a family member leaves the family group, you may be charged for pending purchases made by family members using the family payment method.</p>
<p><strong>Google Payments.</strong> In order to purchase Content through Google Play, you must have a Google Payments account and agree to the Google Payments <a href="https://payments.google.com/customer/tos/viewdocument.html?family=0.buyertos&amp;gl=us" rel="noopener" target="_blank">Terms of Service.</a><a href="https://wallet.google.com/files/privacy.html?hl=en" rel="noopener" target="_blank">The Google Payments Privacy Notice</a> applies whenever you purchase Content using a Google Payments account. You are responsible for all amounts payable associated with purchases made through Google Play on your Google Payments account.</p>
<p><strong>Other Payment Processing Methods.</strong> Google may make available to you various payment processing methods in addition to Google Payments to facilitate the purchase of Content through Google Play. You must abide by any relevant terms and conditions or other legal agreement, whether with Google or a third party, that governs your use of a given payment processing method. Google may add or remove payment processing methods at its sole discretion. You are solely responsible for all amounts payable associated with purchases you make on Google Play.</p>
<p><strong>Eligibility for Carrier Billing.</strong> In order to determine your eligibility to have purchases of Content that you make through your Devices billed to your network provider&rsquo;s account, when you create a Google Play account on a Device, we will send identifiers of your Device, e.g., subscriber ID and SIM card serial number, to your network provider. To permit this you will need to accept the network provider&rsquo;s terms of service. The network provider may send us your billing address information. We will hold and use this information in accordance with Google&rsquo;s <a href="https://www.google.com/intl/en/policies/privacy/" rel="noopener" target="_blank">Privacy Policies</a> and Google Payments <a href="https://wallet.google.com/files/privacy.html?hl=en" rel="noopener" target="_blank">Privacy Notice</a>.</p>
<p><strong>Pricing.</strong> Pricing and availability of all Content displayed through Google Play are subject to change at any time prior to purchase.</p>
<p><strong>Taxes.</strong><strong>"Taxes"</strong> means any duties, customs fees, levies or taxes (other than income tax) associated with the sale of Content, including any related penalties or interest. You are responsible for any Taxes and must pay for Content without any reduction for Taxes. If the seller of Content or Google is obligated to collect or pay Taxes, the Taxes will be charged to you. You must comply with any and all applicable tax laws, including the reporting and payment of any Taxes arising in connection with your use of Google Play or the purchase of Content on or through Google Play. The reporting and payment of any such applicable Taxes are your responsibility.</p>
<p><strong>All Sales Final.</strong> See Google Play&rsquo;s <a href="https://support.google.com/googleplay/answer/2479637" rel="noopener" target="_blank">Refund Policy</a> for more information about your rights to withdraw, cancel, or return purchases for a refund. Except as expressly set out in the Google ToS, Google Play&rsquo;s <a href="https://support.google.com/googleplay/answer/2479637" rel="noopener" target="_blank">Refund Policy</a> or the refund policies of the Provider, all sales are final, and no returns, replacements or refunds are permitted. If a replacement, return or refund is granted for any transaction, the transaction may be reversed, and you may no longer be able to access the Content that you acquired through that transaction.</p>
<p><strong>Subscriptions. </strong>Subscriptions are automatically charged each billing period (whether weekly, monthly, annually, or another period), and you may be charged no earlier than 24 hours before the beginning of each billing period.</p>
<p><strong>(a)</strong><strong>Trials Periods.</strong> When you subscribe to Content for a price, you may receive access to the subscription benefits at no charge for a specified trial period, after which you will be charged until you cancel your subscription. <strong>To avoid being charged, you must cancel before the end of the trial period.</strong> Once you cancel your trial, you will immediately lose access to the Content and any subscription privileges unless otherwise specified. Access to such trial periods may be limited to a certain number of trials for each user during a given period, or other restrictions.</p>
<p><strong>(b)</strong><strong>Cancellations.</strong> You may cancel a subscription at any time before the end of the applicable billing period as described in the <a href="https://support.google.com/googleplay/?hl=en" rel="noopener" target="_blank">Help Center</a>, and the cancellation will apply to the next period. For example, if you purchase a monthly subscription, you may cancel that subscription at any time during any month of the subscription, and the subscription will be cancelled at the end of your then-current billing period. You will not receive a refund for the current billing period, except as otherwise provided in <a href="https://support.google.com/googleplay/answer/2479637" rel="noopener" target="_blank">Google Play&rsquo;s Refund Policy</a> (for example where Content is defective).</p>
<p><strong>(c)</strong><strong>Reductions for Print Subscribers.</strong> Some Providers of periodicals may allow you to purchase a subscription of periodical Content on Google Play at a reduced rate if you are already a print subscriber. If you cancel your print subscription of that periodical or your print subscription expires and you do not renew it, your reduced subscription rate of that Content on Google Play will be cancelled automatically.</p>
<p><strong>(d)</strong><strong>Price Increases.</strong> When you purchase a subscription, you will initially be charged at the rate applicable at the time of your agreement to subscribe. If the price of the subscription increases later, Google will notify you. The increase will apply to the next payment due from you after the notice, provided that you have been given at least 30 days' prior notice before the charge is made. If you are given less than 30 days' prior notice, the price increase will not apply until the payment after the next payment due. If you do not wish to pay the increased price for a subscription, you may cancel the subscription as described in the Cancellations section of these Terms, and you will not be charged further amounts for the subscription, provided you have notified us before the end of the current billing period. Where the Provider increases the price of a subscription and consent is required, Google may cancel your subscription unless you agree to the new price. If your subscription is cancelled and you later decide to re-subscribe, you will be charged at the then current subscription rate.</p>
<h2><strong>4. Rights and Restrictions</strong></h2>
<p><strong>License to Use Content.</strong> After completing a transaction or paying the applicable fees for Content, you will have the non-exclusive right, solely as expressly permitted in these Terms and associated policies, to store, access, view, use, and display copies of the applicable Content on your Devices or as otherwise authorized for your personal, non-commercial use only. All rights, title and interest in Google Play and Content not expressly granted to you in the Terms are reserved. Your use of apps and games may be governed by the additional terms and conditions of the end user license agreement between you and the Provider.</p>
<p><strong>Violation of License Terms.</strong> If you violate any of the Terms, your rights under this license will immediately terminate, and Google may terminate your access to Google Play, the Content or your Google Account without refund to you.</p>
<p><strong>Restrictions</strong>: You may not:</p>
<ul>
<li>display (in part or in whole) the Content as part of any public performance or display even if no fee is charged except (a) where such use would not constitute a copyright infringement or violate any other applicable right or (b) as specifically permitted and only in the exact manner provided.</li>
</ul>
<ul>
<li>sell, rent, lease, redistribute, broadcast, transmit, communicate, modify, sublicense, transfer, assign any Content to any third party including with regard to any downloads of Content that you may obtain through Google Play except as specifically permitted and only in the exact manner provided.</li>
</ul>
<ul>
<li>use Google Play or any Content in conjunction with any stream-ripping, stream capture or similar software to record or create a copy of any Content that is presented to you in streaming format.</li>
</ul>
<ul>
<li>use Content as part of any service for sharing, lending or multi-person use, or for the purpose of any other institution, except as specifically permitted and only in the exact manner provided.</li>
</ul>
<ul>
<li>attempt to, or assist, authorize or encourage others to circumvent, disable or defeat any of the security features or components that protect, obfuscate or otherwise restrict access to any Content or Google Play.</li>
</ul>
<ul>
<li>remove any watermarks, labels or other legal or proprietary notices included in any Content, or attempt to modify any Content obtained through Google Play, including any modification for the purpose of disguising or changing any indications of the ownership or source of Content.</li>
</ul>
<p><strong>Third-Party Provisions.</strong> Notwithstanding anything to the contrary in these Terms, the third parties who license their Content to Google are intended third party beneficiaries under these Terms solely with respect to the specific provisions of these Terms that directly concern their Content (<strong>&ldquo;Third-Party Provisions&rdquo;</strong>), and solely for the purpose of enabling such third parties to enforce their rights in such Content. For the avoidance of doubt, nothing in these Terms confers a third-party beneficiary right upon any party, with respect to any provision that falls outside the Third Party Provisions, which includes but is not limited to any provisions or agreements incorporated by reference, or that may be referenced without incorporation, in these Terms.</p>
<p><strong>Play Policies.</strong>Posting reviews on Google Play is subject to the following<a href="https://play.google.com/about/comment-posting-policy.html">policies</a>. If you want to report abuse or other content violations, click <a href="https://support.google.com/googleplay/answer/2853570" rel="noopener" target="_blank">here</a>.</p>
<p><strong>Defective Content.</strong> Once Content is available to you through your account, you should check the Content as soon as reasonably possible to ensure that it functions and performs as stated, and notify us or Provider as soon as reasonably possible if you find any errors or defect. See the <a href="https://support.google.com/googleplay/answer/2479637" rel="noopener" target="_blank">Google Play Refund Policy</a> for more information.</p>
<p><strong>Removal or Unavailability of Content.</strong> Subject to the Terms, Content that you purchase or install will be available to you through Google Play for the period selected by you, in the case of a purchase for a rental period, and in other cases as long as Google has the right to make such Content available to you. In certain cases (for example if Google loses the relevant rights, a service or Content is discontinued, there are critical security issues, or there are breaches of applicable terms or the law), Google may remove from your Device or cease providing you with access to certain Content that you have purchased. For Content sold by Google LLC, you may be given notice of any such removal or cessation, when possible. If you are not able to download a copy of the Content before such removal or cessation, Google may offer you either (a) a replacement of the Content if possible or (b) a full or partial refund of the price of the Content. If Google issues you a refund, the refund shall be your sole remedy.</p>
<p><strong>Multiple Accounts.</strong> If you have multiple Google Accounts with different user names, in some cases you may transfer Content out of an account and into another account, provided you are the owner of each such account and provided Google has enabled a feature of the relevant service allowing such transfers.</p>
<p><strong>Limits on access on Devices.</strong> Google may from time to time place limits on the number of Devices or software applications you may use to access Content. Please visit the <a href="https://play.google.com/about/movies-tv-usage-rules/">Google Play Movies &amp; TV/Google TV Usages Rules</a> for more information about these limits for Google Play Movies &amp; TV/Google TV.</p>
<p><strong>Dangerous Activities.</strong> None of the Services or Content are intended for use in the operation of nuclear facilities, life support systems, emergency communications, aircraft navigation or communication systems, air traffic control systems, or any other such activities in which case the failure of the Services or Content could lead to death, personal injury, or severe physical or environmental damage.</p>
<p><strong>Google Play Movies &amp; TV/Google TV.</strong> For additional details and restrictions regarding your access and use of Google Play Movies &amp; TV/Google TV, see the <a href="https://docs.google.com/document/d/1gKEwgGP2NgUauCmLYBEoOvxE0rsTYoGaS9ZOZA42Fl8/edit" rel="noopener" target="_blank">Google Play Movies &amp; TV/Google TV Usage Rules.&nbsp;</a></p>
      
      
</div>
  )
}

export default ToS